DROP TABLE IF EXISTS mmwe.tqmtiwea13;

CREATE TABLE mmwe.tqmtiwea13 (
    OPERATOR_FLAG VARCHAR(1) NOT NULL DEFAULT ' ',
    PROD_DATE VARCHAR(8) NOT NULL DEFAULT ' ',
    PROD_TM VARCHAR(6) NOT NULL DEFAULT ' ',
    PROD_SHIFT_NO VARCHAR(1) NOT NULL DEFAULT ' ',
    PROD_SHIFT_GROUP VARCHAR(1) NOT NULL DEFAULT ' ',
    PROD_JOB_POINT VARCHAR(4) NOT NULL DEFAULT ' ',
    DEST_CODE VARCHAR(4) NOT NULL DEFAULT ' ',
    ORDER_NO VARCHAR(10) NOT NULL,
    ORDER_ITEM_NO VARCHAR(3) NOT NULL,
    PROD_CODE VARCHAR(1) NOT NULL DEFAULT ' ',
    PROD_CNAME VARCHAR(30) NOT NULL DEFAULT ' ',
    ORDER_OUTER_DIA NUMERIC(6, 2) NOT NULL DEFAULT 0,
    ORDER_WAL_THICK NUMERIC(5, 2) NOT NULL DEFAULT 0,
    ORDER_HEIGHT NUMERIC(6, 2) NOT NULL DEFAULT 0,
    STD_SG_CODE VARCHAR(4) NOT NULL DEFAULT ' ',
    SG_SIGN VARCHAR(50) NOT NULL DEFAULT ' ',
    SG_STD VARCHAR(100) NOT NULL DEFAULT ' ',
    MTRL_NO VARCHAR(4) NOT NULL DEFAULT ' ',
    MTRL_TEXT VARCHAR(50) NOT NULL DEFAULT ' ',
    PIPEEND_TYPE_CODE VARCHAR(1) NOT NULL DEFAULT ' ',
    PIPEEND_TYPE_SIGN VARCHAR(12) NOT NULL DEFAULT ' ',
    PIPEEND_TYPE VARCHAR(30) NOT NULL DEFAULT ' ',
    THREAD_TYPE_CODE VARCHAR(1) NOT NULL DEFAULT ' ',
    THREAD_TYPE_SIGN VARCHAR(12) NOT NULL DEFAULT ' ',
    THREAD_TYPE VARCHAR(30) NOT NULL DEFAULT ' ',
    OLD_ORDER_NO VARCHAR(10) NOT NULL DEFAULT ' ',
    RL_NO VARCHAR(10) NOT NULL DEFAULT ' ',
    PONO VARCHAR(10) NOT NULL DEFAULT ' ',
    SAMPLE_LOT_NO VARCHAR(12) NOT NULL DEFAULT ' ',
    MAT_NO VARCHAR(20) NOT NULL DEFAULT ' ',
    BUNDLE_TYPE VARCHAR(3) NOT NULL DEFAULT ' ',
    MAT_TUBE INTEGER NOT NULL DEFAULT 0,
    MAT_ACT_WT NUMERIC(9, 3) NOT NULL DEFAULT 0,
    MAT_ENG_WT NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TOTAL_LEN NUMERIC(9, 3) NOT NULL DEFAULT 0,
    ENG_TOTAL_LEN NUMERIC(9, 3) NOT NULL DEFAULT 0,
    LEN_FROM NUMERIC(9, 3) NOT NULL DEFAULT 0,
    LEN_TO NUMERIC(9, 3) NOT NULL DEFAULT 0,
    MAT_THEORY_WT NUMERIC(9, 3) NOT NULL DEFAULT 0,
    THY_TOTAL_LEN NUMERIC(9, 3) NOT NULL DEFAULT 0,
    ORDER_END_FLAG VARCHAR(1) NOT NULL DEFAULT ' ',
    CTL_TUBE_DIA_FROM NUMERIC(7, 3) NOT NULL DEFAULT 0,
    CTL_TUBE_DIA_TO NUMERIC(7, 3) NOT NULL DEFAULT 0,
    CTL_WAL_THICK_FROM NUMERIC(5, 2) NOT NULL DEFAULT 0,
    CTL_WAL_THICK_TO NUMERIC(5, 2) NOT NULL DEFAULT 0,
    CTL_HEIGHT_FROM NUMERIC(7, 2) NOT NULL DEFAULT 0,
    CTL_HEIGHT_TO NUMERIC(7, 2) NOT NULL DEFAULT 0,
    COUP_PONO VARCHAR(10) NOT NULL DEFAULT ' ',
    COUP_SAMPLE_LOT_NO VARCHAR(12) NOT NULL DEFAULT ' ',
    PROTECT_SIZE VARCHAR(12) NOT NULL DEFAULT ' ',
    PROTECT_LOT_NO VARCHAR(7) NOT NULL DEFAULT ' ',
    PROTECT_FACTORY VARCHAR(60) NOT NULL DEFAULT ' ',
    COMPOUND_SIZE VARCHAR(12) NOT NULL DEFAULT ' ',
    COMPOUND_LOT_NO VARCHAR(7) NOT NULL DEFAULT ' ',
    COMPOUND_FACTORY VARCHAR(60) NOT NULL DEFAULT ' ',
    COATING_SIZE VARCHAR(12) NOT NULL DEFAULT ' ',
    COATING_LOT_NO VARCHAR(7) NOT NULL DEFAULT ' ',
    COATING_FACTORY VARCHAR(60) NOT NULL DEFAULT ' ',
    STOCK_PLACE_NO VARCHAR(15) NOT NULL DEFAULT ' ',
    TUBE_NO_1 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_1 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_1 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_1 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_1 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_1 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_1 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_1 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_2 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_2 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_2 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_2 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_2 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_2 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_2 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_2 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_3 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_3 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_3 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_3 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_3 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_3 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_3 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_3 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_4 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_4 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_4 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_4 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_4 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_4 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_4 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_4 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_5 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_5 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_5 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_5 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_5 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_5 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_5 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_5 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_6 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_6 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_6 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_6 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_6 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_6 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_6 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_6 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_7 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_7 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_7 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_7 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_7 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_7 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_7 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_7 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_8 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_8 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_8 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_8 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_8 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_8 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_8 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_8 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_9 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_9 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_9 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_9 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_9 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_9 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_9 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_9 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_10 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_10 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_10 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_10 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_10 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_10 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_10 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_10 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_11 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_11 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_11 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_11 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_11 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_11 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_11 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_11 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_12 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_12 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_12 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_12 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_12 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_12 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_12 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_12 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_13 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_13 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_13 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_13 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_13 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_13 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_13 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_13 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_14 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_14 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_14 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_14 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_14 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_14 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_14 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_14 INTEGER NOT NULL DEFAULT 0,
    TUBE_NO_15 VARCHAR(7) DEFAULT ' ',
    TUBE_ACT_WT_15 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_WT_15 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_THEORY_WT_15 NUMERIC(9, 3) NOT NULL DEFAULT 0,
    TUBE_LEN_15 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_ENG_LEN_15 NUMERIC(6, 3) NOT NULL DEFAULT 0,
    TUBE_THY_LEN_15 NUMERIC(7, 3) NOT NULL DEFAULT 0,
    SEQ_ID_15 INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ORDER_NO, ORDER_ITEM_NO, MAT_NO)
);

COMMENT ON COLUMN mmwe.tqmtiwea13.OPERATOR_FLAG IS '增删标记';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_DATE IS '生产日期';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_TM IS '生产时间(6位)';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_SHIFT_NO IS '生产班次';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_SHIFT_GROUP IS '生产班组';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_JOB_POINT IS '生产作业点';
COMMENT ON COLUMN mmwe.tqmtiwea13.DEST_CODE IS '去向代码';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_NO IS '合同号';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_ITEM_NO IS '合同项目号';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_CODE IS '品名细分类代码';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROD_CNAME IS '品名细分类中文';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_OUTER_DIA IS '外径';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_WAL_THICK IS '壁厚';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_HEIGHT IS '高度';
COMMENT ON COLUMN mmwe.tqmtiwea13.STD_SG_CODE IS '标准牌号(钢级)代码';
COMMENT ON COLUMN mmwe.tqmtiwea13.SG_SIGN IS '牌号（钢级）';
COMMENT ON COLUMN mmwe.tqmtiwea13.SG_STD IS '牌号标准(标准正文)';
COMMENT ON COLUMN mmwe.tqmtiwea13.MTRL_NO IS '材质号';
COMMENT ON COLUMN mmwe.tqmtiwea13.MTRL_TEXT IS '材质正文';
COMMENT ON COLUMN mmwe.tqmtiwea13.PIPEEND_TYPE_CODE IS '管端型式代码';
COMMENT ON COLUMN mmwe.tqmtiwea13.PIPEEND_TYPE_SIGN IS '管端型式符号';
COMMENT ON COLUMN mmwe.tqmtiwea13.PIPEEND_TYPE IS '管端型式';
COMMENT ON COLUMN mmwe.tqmtiwea13.THREAD_TYPE_CODE IS '螺纹类型代码';
COMMENT ON COLUMN mmwe.tqmtiwea13.THREAD_TYPE_SIGN IS '螺纹类型符号';
COMMENT ON COLUMN mmwe.tqmtiwea13.THREAD_TYPE IS '螺纹类型';
COMMENT ON COLUMN mmwe.tqmtiwea13.OLD_ORDER_NO IS '原合同号';
COMMENT ON COLUMN mmwe.tqmtiwea13.RL_NO IS '轧批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.PONO IS '制造命令号(炉号)';
COMMENT ON COLUMN mmwe.tqmtiwea13.SAMPLE_LOT_NO IS '试批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.MAT_NO IS '材料号(管捆号)';
COMMENT ON COLUMN mmwe.tqmtiwea13.BUNDLE_TYPE IS '管捆类型';
COMMENT ON COLUMN mmwe.tqmtiwea13.MAT_TUBE IS '材料根数';
COMMENT ON COLUMN mmwe.tqmtiwea13.MAT_ACT_WT IS '材料重量(吨)';
COMMENT ON COLUMN mmwe.tqmtiwea13.MAT_ENG_WT IS '材料英制重量';
COMMENT ON COLUMN mmwe.tqmtiwea13.TOTAL_LEN IS '总长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.ENG_TOTAL_LEN IS '英制总长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.LEN_FROM IS '长度起';
COMMENT ON COLUMN mmwe.tqmtiwea13.LEN_TO IS '长度止';
COMMENT ON COLUMN mmwe.tqmtiwea13.MAT_THEORY_WT IS '材料理论重量';
COMMENT ON COLUMN mmwe.tqmtiwea13.THY_TOTAL_LEN IS '理论总长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.ORDER_END_FLAG IS '合同结束标记';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_TUBE_DIA_FROM IS '内控管体外径起';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_TUBE_DIA_TO IS '内控管体外径止';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_WAL_THICK_FROM IS '内控壁厚起';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_WAL_THICK_TO IS '内控壁厚止';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_HEIGHT_FROM IS '内控高度起';
COMMENT ON COLUMN mmwe.tqmtiwea13.CTL_HEIGHT_TO IS '内控高度止';
COMMENT ON COLUMN mmwe.tqmtiwea13.COUP_PONO IS '接箍炉号';
COMMENT ON COLUMN mmwe.tqmtiwea13.COUP_SAMPLE_LOT_NO IS '接箍试批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROTECT_SIZE IS '保护环规格';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROTECT_LOT_NO IS '保护环批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.PROTECT_FACTORY IS '保护环生产厂家';
COMMENT ON COLUMN mmwe.tqmtiwea13.COMPOUND_SIZE IS '螺纹脂规格';
COMMENT ON COLUMN mmwe.tqmtiwea13.COMPOUND_LOT_NO IS '螺纹脂批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.COMPOUND_FACTORY IS '螺纹脂生产厂家';
COMMENT ON COLUMN mmwe.tqmtiwea13.COATING_SIZE IS '防腐涂层规格';
COMMENT ON COLUMN mmwe.tqmtiwea13.COATING_LOT_NO IS '防腐涂层批号';
COMMENT ON COLUMN mmwe.tqmtiwea13.COATING_FACTORY IS '防腐涂层生产厂家';
COMMENT ON COLUMN mmwe.tqmtiwea13.STOCK_PLACE_NO IS '材料库位号';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_1 IS '管号1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_1 IS '单根管子重量1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_1 IS '单根管子英制重量1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_1 IS '单根管子理论重量1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_1 IS '单根管子长度1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_1 IS '单根管子英制长度1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_1 IS '单根管子理论长度1';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_1 IS '流水号1';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_2 IS '管号2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_2 IS '单根管子重量2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_2 IS '单根管子英制重量2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_2 IS '单根管子理论重量2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_2 IS '单根管子长度2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_2 IS '单根管子英制长度2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_2 IS '单根管子理论长度2';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_2 IS '流水号2';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_3 IS '管号3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_3 IS '单根管子重量3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_3 IS '单根管子英制重量3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_3 IS '单根管子理论重量3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_3 IS '单根管子长度3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_3 IS '单根管子英制长度3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_3 IS '单根管子理论长度3';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_3 IS '流水号3';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_4 IS '管号4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_4 IS '单根管子重量4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_4 IS '单根管子英制重量4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_4 IS '单根管子理论重量4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_4 IS '单根管子长度4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_4 IS '单根管子英制长度4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_4 IS '单根管子理论长度4';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_4 IS '流水号4';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_5 IS '管号5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_5 IS '单根管子重量5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_5 IS '单根管子英制重量5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_5 IS '单根管子理论重量5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_5 IS '单根管子长度5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_5 IS '单根管子英制长度5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_5 IS '单根管子理论长度5';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_5 IS '流水号5';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_6 IS '管号6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_6 IS '单根管子重量6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_6 IS '单根管子英制重量6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_6 IS '单根管子理论重量6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_6 IS '单根管子长度6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_6 IS '单根管子英制长度6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_6 IS '单根管子理论长度6';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_6 IS '流水号6';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_7 IS '管号7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_7 IS '单根管子重量7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_7 IS '单根管子英制重量7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_7 IS '单根管子理论重量7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_7 IS '单根管子长度7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_7 IS '单根管子英制长度7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_7 IS '单根管子理论长度7';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_7 IS '流水号7';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_8 IS '管号8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_8 IS '单根管子重量8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_8 IS '单根管子英制重量8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_8 IS '单根管子理论重量8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_8 IS '单根管子长度8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_8 IS '单根管子英制长度8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_8 IS '单根管子理论长度8';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_8 IS '流水号8';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_9 IS '管号9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_9 IS '单根管子重量9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_9 IS '单根管子英制重量9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_9 IS '单根管子理论重量9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_9 IS '单根管子长度9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_9 IS '单根管子英制长度9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_9 IS '单根管子理论长度9';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_9 IS '流水号9';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_10 IS '管号10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_10 IS '单根管子重量10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_10 IS '单根管子英制重量10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_10 IS '单根管子理论重量10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_10 IS '单根管子长度10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_10 IS '单根管子英制长度10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_10 IS '单根管子理论长度10';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_10 IS '流水号10';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_11 IS '管号11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_11 IS '单根管子重量11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_11 IS '单根管子英制重量11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_11 IS '单根管子理论重量11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_11 IS '单根管子长度11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_11 IS '单根管子英制长度11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_11 IS '单根管子理论长度11';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_11 IS '流水号11';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_12 IS '管号12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_12 IS '单根管子重量12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_12 IS '单根管子英制重量12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_12 IS '单根管子理论重量12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_12 IS '单根管子长度12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_12 IS '单根管子英制长度12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_12 IS '单根管子理论长度12';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_12 IS '流水号12';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_13 IS '管号13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_13 IS '单根管子重量13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_13 IS '单根管子英制重量13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_13 IS '单根管子理论重量13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_13 IS '单根管子长度13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_13 IS '单根管子英制长度13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_13 IS '单根管子理论长度13';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_13 IS '流水号13';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_14 IS '管号14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_14 IS '单根管子重量14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_14 IS '单根管子英制重量14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_14 IS '单根管子理论重量14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_14 IS '单根管子长度14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_14 IS '单根管子英制长度14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_14 IS '单根管子理论长度14';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_14 IS '流水号14';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_NO_15 IS '管号15';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ACT_WT_15 IS '单根管子重量15';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_WT_15 IS '单根管子英制重量15';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THEORY_WT_15 IS '单根管子理论重量15';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_LEN_15 IS '单根管子长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_ENG_LEN_15 IS '单根管子英制长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.TUBE_THY_LEN_15 IS '单根管子理论长度';
COMMENT ON COLUMN mmwe.tqmtiwea13.SEQ_ID_15 IS '流水号';